# Generated by Django 4.1 on 2024-08-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BudgetEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inout",
                    models.CharField(
                        choices=[("income", "Income"), ("outcome", "Outcome")],
                        max_length=7,
                    ),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("last_edit_date", models.DateTimeField(auto_now_add=True)),
                ("amount", models.IntegerField()),
                ("category", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=255)),
            ],
        ),
    ]
