# Generated by Django 4.1 on 2024-08-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetentry",
            name="owner",
            field=models.CharField(default="Not Known", max_length=16),
        ),
    ]
