# Generated by Django 4.1 on 2024-08-27 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0002_budgetentry_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budgetentry",
            name="create_date",
        ),
        migrations.RemoveField(
            model_name="budgetentry",
            name="last_edit_date",
        ),
        migrations.AddField(
            model_name="budgetentry",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="budgetentry",
            name="inout",
            field=models.CharField(
                choices=[("Income", "Income"), ("Outcome", "Outcome")], max_length=7
            ),
        ),
    ]
