# Generated by Django 4.1 on 2024-08-27 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0003_remove_budgetentry_create_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetentry",
            name="created",
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
