# Generated by Django 4.1 on 2024-10-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0005_alter_budgetentry_created"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilterFormModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "income_or_expense",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Income", "Income"),
                            ("Outcome", "Outcome"),
                            ("Invest", "Invest"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("January", "January"),
                            ("February", "February"),
                            ("March", "March"),
                            ("April", "April"),
                            ("May", "May"),
                            ("June", "June"),
                            ("July", "July"),
                            ("August", "August"),
                            ("September", "September"),
                            ("October", "October"),
                            ("November", "November"),
                            ("December", "December"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Yemek", "Yemek"),
                            ("Tasarruf", "Tasarruf"),
                            ("Fatura", "Fatura"),
                            ("Alışveriş", "Alışveriş"),
                            ("Kira", "Kira"),
                            ("Ulaşım", "Ulaşım"),
                        ],
                        max_length=12,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="budgetentry",
            name="inout",
            field=models.CharField(
                choices=[
                    ("Income", "Income"),
                    ("Outcome", "Outcome"),
                    ("Invest", "Invest"),
                ],
                max_length=7,
            ),
        ),
    ]
