# Generated by Django 4.2.5 on 2023-09-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_alter_task_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="owner",
            field=models.CharField(default="Not Known", max_length=16),
        ),
    ]
