# Generated by Django 4.2.5 on 2023-10-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("province", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("latitude", models.DecimalField(decimal_places=5, max_digits=8)),
                ("longtitude", models.DecimalField(decimal_places=5, max_digits=8)),
            ],
        ),
    ]
